services:
  - type: web
    name: laravel-breeze-app
    env: docker
    buildCommand: "docker build -t laravel-breeze-app ."
    startCommand: "docker run -p 8080:80 --log-driver json-file laravel-breeze-app"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Ze+cwZzvHuWKXHkkWaIIJs8YNRU7FVHw6sTtopoH168=
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://twiiter-vpzs.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cgl1fiu4dad69r5eqelg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: twiiter
      - key: DB_USERNAME
        value: sakosuta
      - key: DB_PASSWORD
        value: lKqrZRJEqkFAliHOJCxlJu3v7JlFg1R6
        

databases:
  - name: twiiter
    engine: postgres
    version: "15"
    username: sakosuta
    password: lKqrZRJEqkFAliHOJCxlJu3v7JlFg1R6
    port: 5432
    database: twiiter